apiVersion: v1
kind: Service
metadata:
  labels:
    v1.min.io/tenant: microk8s
  name: microk8s-hl-cluster-ip
  namespace: minio-operator
spec:
  ports:
  - name: http-minio
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    v1.min.io/tenant: microk8s
  type: ClusterIP