[pytest]
addopts = -s -m "not slow"
testpaths = tests src
python_files = test_*.py

# register the "slow" marker so pytest doesn't warn when it's used
markers =
    slow: marks tests as slow (deselect with -m "not slow")
asyncio_mode=auto
log_level=INFO
log_cli=true
norecursedirs = .git .venv src pyright docker-volumes

filterwarnings =
    # DeprecationWarning: This process (pid=35619) is multi-threaded, use of fork() may lead to deadlocks in the child.
    ignore:.*fork\(\) may lead to deadlocks in the child.*:DeprecationWarning
    # DeprecationWarning: datetime.datetime.utcnow() is deprecated
    ignore:datetime\.datetime\.utcnow\(\) is deprecated.*:DeprecationWarning
    # DeprecationWarning: websockets.legacy is deprecated
    ignore:websockets\.legacy is deprecated.*:DeprecationWarning
    # DeprecationWarning: websockets.server.WebSocketServerProtocol is deprecated
    ignore:.*WebSocketServerProtocol is deprecated.*:DeprecationWarning
    # DeprecationWarning: remove second argument of ws_handler
    ignore:remove second argument of ws_handler.*:DeprecationWarning

env =
    QUICKLOOK_environment=test
    R:QUICKLOOK_s3_test_data={"access_key": "quicklook", "secret_key": "password", "endpoint": "10.152.183.240:9000", "secure": false, "bucket": "fov-quicklook-datasource", "type": "minio"}
    R:QUICKLOOK_s3_tile={"access_key": "quicklook", "secret_key": "password", "endpoint": "10.152.183.240:9000", "secure": false, "bucket": "fov-quicklook-tile", "type": "minio"}
    R:QUICKLOOK_data_source=dummy
    QUICKLOOK_dev_generator_required_coordinator_connection=false
    QUICKLOOK_db_url=postgresql+asyncpg://quicklook:quicklook@localhost:5432/quicklook
