[pytest]
addopts = --cov=quicklook --cov-report=html -s
testpaths = tests src
python_files = test_*.py
asyncio_mode=auto
log_level=INFO
log_cli=true
norecursedirs = .git .venv src

filterwarnings =
    # DeprecationWarning: This process (pid=35619) is multi-threaded, use of fork() may lead to deadlocks in the child.
    ignore:.*fork\(\) may lead to deadlocks in the child.*:DeprecationWarning
    # DeprecationWarning: datetime.datetime.utcnow() is deprecated
    ignore:datetime\.datetime\.utcnow\(\) is deprecated.*:DeprecationWarning

env =
    QUICKLOOK_environment=test
    R:QUICKLOOK_s3_test_data={"access_key": "quicklook", "secret_key": "password", "endpoint": "10.152.183.240:9000", "secure": false, "bucket": "fov-quicklook-datasource"}
    R:QUICKLOOK_data_source=dummy
