apiVersion: apps/v1
kind: Deployment
metadata:
  name: quicklook-coordinator
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: quicklook-coordinator
  template:
    metadata:
      labels:
        app: quicklook-coordinator
    spec:
      containers:
        - name: quicklook-coordinator
          image: {{ .Values.quicklook_image }}
          command:
            - sh
            - -c
            - |
              set -e
              alembic upgrade head
              exec python -m quicklook.coordinator.api
          env:
            - name: QUICKLOOK_db_url
              value: postgresql://quicklook:quicklook@quicklook-db:5432/quicklook
            - name: QUICKLOOK_s3_repository
              value: {{ .Values.s3_repository | toJson | quote }}
            - name: QUICKLOOK_s3_tile
              value: {{ .Values.s3_tile | toJson | quote }}
          ports:
            - containerPort: 9501
---
apiVersion: v1
kind: Service
metadata:
  name: quicklook-coordinator
spec:
  selector:
    app: quicklook-coordinator
  # type: ClusterIP
  # clusterIP: None
  type: NodePort
  nodePort: 32002
  ports:
    - name: http
      protocol: TCP
      port: 9501
      targetPort: 9501
