apiVersion: apps/v1
kind: Deployment
metadata:
  name: quicklook-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quicklook-frontend
  template:
    metadata:
      labels:
        app: quicklook-frontend
    spec:
      containers:
        - name: quicklook-frontend
          image: {{ .Values.quicklook_image }}
          command:
            - sh
            - -c
            - |
              exec python -m quicklook.frontend.api
          env:
            - name: QUICKLOOK_coordinator_base_url
              value: http://quicklook-coordinator:9501
          ports:
            - containerPort: 9500
---
apiVersion: v1
kind: Service
metadata:
  name: quicklook-frontend
spec:
  selector:
    app: quicklook-frontend
  type: LoadBalancer
  # loadBalancerIP is optional. MetalLB will automatically allocate an IP
  # from its pool if not specified. You can also specify one manually.
  loadBalancerIP: 192.168.13.202
  ports:
    - name: http
      protocol: TCP
      port: 9500
      targetPort: 9500
