"""Initial migration: add quicklooks and accesses tables

Revision ID: ce01d9bd7d44
Revises: 
Create Date: 2025-10-07 17:34:56.597093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce01d9bd7d44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quicklooks',
    sa.Column('visit_name', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('disk_usage', sa.Integer(), nullable=False),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('visit_name'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('accesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visit_name', sa.String(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['visit_name'], ['quicklooks.visit_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accesses')
    op.drop_table('quicklooks')
    # ### end Alembic commands ###
